# Generated by Django 4.1.3 on 2022-12-03 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0004_alter_ads_category_alter_ads_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Админ')], default='member', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('items', models.ManyToManyField(to='aaa.ads')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaa.user')),
            ],
        ),
    ]
